from __future__ import annotations

from .closeout import LEGACY_CLOSEOUT_COMMAND_MODULES
from .continuous_upgrade import LEGACY_CONTINUOUS_UPGRADE_COMMAND_MODULES
from .foundation import LEGACY_FOUNDATION_COMMAND_MODULES, LEGACY_NAMESPACE_COMMANDS

LEGACY_COMMAND_MODULES: dict[str, str] = {
    **LEGACY_FOUNDATION_COMMAND_MODULES,
    **LEGACY_CLOSEOUT_COMMAND_MODULES,
    **LEGACY_CONTINUOUS_UPGRADE_COMMAND_MODULES,
}
