from __future__ import annotations

from .continuous_upgrade import LEGACY_CONTINUOUS_UPGRADE_COMMAND_MODULES
from .foundation import (
    LEGACY_FOUNDATION_COMMAND_MODULES,
)
from .foundation import (
    LEGACY_NAMESPACE_COMMANDS as LEGACY_NAMESPACE_COMMANDS,
)
from .workflow_aliases import CANONICAL_CLOSEOUT_COMMAND_MODULES, LEGACY_CLOSEOUT_COMMAND_MODULES

LEGACY_COMMAND_MODULES: dict[str, str] = {
    **LEGACY_FOUNDATION_COMMAND_MODULES,
    **LEGACY_CLOSEOUT_COMMAND_MODULES,
    **CANONICAL_CLOSEOUT_COMMAND_MODULES,
    **LEGACY_CONTINUOUS_UPGRADE_COMMAND_MODULES,
}
