from __future__ import annotations

from pathlib import Path
from typing import Any

from . import (
    adoption_surface,
    automation_health,
    candidate_collision_checklist,
    candidate_evidence_checklist,
    candidate_freeze_readiness,
    check_intelligence,
    diagnostic_signal_snapshot,
    diagnostic_signal_snapshot_history,
    doctor,
    issue_queue_classifier,
    maintenance_queue_rollup,
    pr_quality_runtime_proof_artifacts,
    protected_verifier,
    replayable_benchmark_harness,
    repo_fit_screen,
    repo_memory,
    review,
    safe_fix_history_memory,
    security_finding_disposition_matrix,
    security_findings_inventory,
    security_followup_disposition,
    trajectory_store,
)
from .checks import artifacts as check_artifacts

INDEX_SCHEMA_VERSION = "sdetkit.artifact-contract-index.v1"


def build_index() -> dict[str, Any]:
    return {
        "schema_version": INDEX_SCHEMA_VERSION,
        "artifacts": [
            {
                "id": "gate-fast-json",
                "path": "build/gate-fast.json",
                "produced_by": "python -m sdetkit gate fast --format json --stable-json --out build/gate-fast.json",
                "schema_version": None,
                "required_fields": ["ok", "failed_steps", "profile"],
                "stability": "public",
            },
            {
                "id": "release-preflight-json",
                "path": "build/release-preflight.json",
                "produced_by": "python -m sdetkit gate release --format json --out build/release-preflight.json",
                "schema_version": None,
                "required_fields": ["ok", "failed_steps", "profile"],
                "stability": "public",
            },
            {
                "id": "diagnostic-signal-snapshot-json",
                "path": (
                    diagnostic_signal_snapshot.DEFAULT_OUT_DIR
                    / diagnostic_signal_snapshot.SNAPSHOT_JSON
                ).as_posix(),
                "produced_by": "python -m sdetkit.diagnostic_signal_snapshot --evidence-narrative <evidence-narrative.json> --evidence-graph <evidence-graph.json> --diagnostic-worker-result <diagnostic-worker-result.json> --runtime-proof-artifacts <runtime-proof-artifacts.json> --security-finding-diagnosis <security-finding-diagnosis.json> --out-dir build/pr-quality/diagnostic-signal-snapshot --format json",
                "schema_version": diagnostic_signal_snapshot.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "snapshot_type",
                    "quiet_green_advisory_baseline",
                    "measurements",
                    "kpi_readiness",
                    "decision_boundary",
                ],
                "stability": "advanced",
            },
            {
                "id": "diagnostic-signal-snapshot-history-summary-json",
                "path": (
                    diagnostic_signal_snapshot_history.DEFAULT_OUT_DIR
                    / diagnostic_signal_snapshot_history.SUMMARY_JSON
                ).as_posix(),
                "produced_by": "python -m sdetkit.diagnostic_signal_snapshot_history --diagnostic-signal-snapshot <diagnostic-signal-snapshot.json> --associated-pr-json <associated-pr.json> --source-run-id <run-id> --source-run-conclusion success --source-head-sha <head-sha> --retention-run-id <retention-run-id> --accepted-main-sha <main-sha> --out-dir build/repo-memory-history/diagnostic-signal-snapshots --format json",
                "schema_version": diagnostic_signal_snapshot_history.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "history_path",
                    "prior_history_collected",
                    "prior_record_count",
                    "appended",
                    "record_count",
                    "quiet_green_advisory_baseline_record_count",
                    "review_signal_record_count",
                    "integration_proof_signal_record_count",
                    "snapshot_status_counts",
                    "advisor_false_positive_rate_status",
                    "latest_record",
                    "decision_boundary",
                ],
                "stability": "advanced",
            },
            {
                "id": "pr-quality-runtime-proof-artifacts-json",
                "path": (
                    pr_quality_runtime_proof_artifacts.DEFAULT_OUT_DIR
                    / pr_quality_runtime_proof_artifacts.SUMMARY_JSON
                ).as_posix(),
                "produced_by": "python -m sdetkit.pr_quality_runtime_proof_artifacts --isolated-proof <isolated-proof.json> --live-benchmark-report <benchmark-report.json> --repo-memory-profile <repo-memory-profile.json> --trusted-history-evidence <trusted-history.json> --out-dir build/pr-quality/runtime-proof/summary --format json",
                "schema_version": pr_quality_runtime_proof_artifacts.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "collected_components",
                    "isolated_proof",
                    "live_benchmark",
                    "repo_memory",
                    "trusted_history",
                    "decision_boundary",
                ],
                "stability": "advanced",
            },
            {
                "id": "protected-verifier-result-json",
                "path": (
                    protected_verifier.DEFAULT_OUT_DIR / protected_verifier.RESULT_JSON
                ).as_posix(),
                "produced_by": "python -m sdetkit.protected_verifier --patch-score <patch-score.json> --verification-evidence <verification-evidence.json> --out-dir build/protected-verifier --format json",
                "schema_version": protected_verifier.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "patch_id",
                    "diagnosis_id",
                    "patch_score",
                    "scored_files",
                    "observed_changed_files",
                    "allowed_files",
                    "proof_requirements",
                    "findings",
                    "decision",
                ],
                "stability": "advanced",
            },
            {
                "id": "replayable-benchmark-report-json",
                "path": (
                    replayable_benchmark_harness.DEFAULT_OUT_DIR
                    / replayable_benchmark_harness.REPORT_JSON
                ).as_posix(),
                "produced_by": "python -m sdetkit.replayable_benchmark_harness --scenario <scenario.json> --out-dir build/replayable-benchmark-harness --format json",
                "schema_version": replayable_benchmark_harness.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "scenario_count",
                    "passed_count",
                    "failed_count",
                    "required_contract",
                    "safety_boundary",
                    "attempt_scored_count",
                    "scenarios",
                    "next_boundary",
                ],
                "stability": "advanced",
            },
            {
                "id": "trajectory-jsonl",
                "path": trajectory_store.DEFAULT_OUT,
                "produced_by": "python -m sdetkit.trajectory_store --diagnostic-vector <diagnostic-vector.json> --remediation-plan <remediation-plan.json> --out build/sdetkit/trajectory.jsonl --format json",
                "schema_version": trajectory_store.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "trajectory_id",
                    "environment",
                    "diagnosis",
                    "decision",
                    "response",
                    "fix",
                    "final_result",
                ],
                "stability": "advanced",
            },
            {
                "id": "repo-memory-profile-json",
                "path": (repo_memory.DEFAULT_OUT_DIR / repo_memory.PROFILE_JSON).as_posix(),
                "produced_by": "python -m sdetkit.repo_memory --out-dir build/repo-memory --format json",
                "schema_version": repo_memory.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "profile_status",
                    "memory_mode",
                    "inputs",
                    "safe_fix_history",
                    "known_safe_candidate_count",
                ],
                "stability": "advanced",
            },
            {
                "id": "safe-fix-history-json",
                "path": f"{safe_fix_history_memory.DEFAULT_OUT_DIR}/{safe_fix_history_memory.HISTORY_JSON}",
                "produced_by": "python -m sdetkit.safe_fix_history_memory --out-dir build/operator-loop/safe-fix-history",
                "schema_version": safe_fix_history_memory.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "attempts",
                    "metrics",
                ],
                "stability": "advanced",
            },
            {
                "id": "safe-fix-trends-json",
                "path": f"{safe_fix_history_memory.DEFAULT_OUT_DIR}/{safe_fix_history_memory.TRENDS_JSON}",
                "produced_by": "python -m sdetkit.safe_fix_history_memory --out-dir build/operator-loop/safe-fix-history",
                "schema_version": safe_fix_history_memory.TRENDS_SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "metrics",
                ],
                "stability": "advanced",
            },
            {
                "id": "check-intelligence-json",
                "path": "build/pr-quality/check-intelligence.json",
                "produced_by": "python -m sdetkit.check_intelligence --checks-json <checks.json> --out-dir build/pr-quality",
                "schema_version": check_intelligence.CHECK_INTELLIGENCE_SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "checks_seen",
                    "failed_checks",
                    "queued_checks",
                    "startup_failures",
                    "real_evidence_quality",
                    "security_review",
                    "code_scanning_review",
                ],
                "stability": "advanced",
            },
            {
                "id": "check-intelligence-action-report-json",
                "path": "build/pr-quality/action-report.json",
                "produced_by": "python -m sdetkit.check_intelligence --checks-json <checks.json> --out-dir build/pr-quality",
                "schema_version": check_intelligence.ACTION_REPORT_SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "primary_blocker",
                    "automation",
                    "recommended_actions",
                    "proof_commands",
                    "evidence",
                ],
                "stability": "advanced",
            },
            {
                "id": "candidate-collision-checklist-json",
                "path": candidate_collision_checklist.DEFAULT_OUT,
                "produced_by": "python -m sdetkit candidate-collision-checklist --evidence-checklist-json <candidate-evidence-checklist.json> --out build/sdetkit/candidate-collision-checklist.json --format text",
                "schema_version": candidate_collision_checklist.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "repo",
                    "commit",
                    "evidence_checklist_schema",
                    "candidate_frozen",
                    "freeze_ready",
                    "missing_issue_collision_review",
                    "collision_check_count",
                    "missing_collision_check_count",
                    "collision_checks",
                    "hard_blocks",
                    "recommended_action",
                    "automation_allowed",
                    "merge_authorized",
                    "semantic_equivalence_proven",
                ],
                "stability": "advanced",
            },
            {
                "id": "candidate-evidence-checklist-json",
                "path": candidate_evidence_checklist.DEFAULT_OUT,
                "produced_by": "python -m sdetkit candidate-evidence-checklist --readiness-json <candidate-freeze-readiness.json> --out build/sdetkit/candidate-evidence-checklist.json --format text",
                "schema_version": candidate_evidence_checklist.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "repo",
                    "commit",
                    "readiness_schema",
                    "readiness_status",
                    "candidate_frozen",
                    "freeze_ready",
                    "required_item_count",
                    "missing_item_count",
                    "present_item_count",
                    "checklist_items",
                    "hard_blocks",
                    "recommended_action",
                    "automation_allowed",
                    "merge_authorized",
                    "semantic_equivalence_proven",
                ],
                "stability": "advanced",
            },
            {
                "id": "candidate-freeze-readiness-json",
                "path": candidate_freeze_readiness.DEFAULT_OUT,
                "produced_by": "python -m sdetkit candidate-freeze-readiness --repo-fit-json <repo-fit-screen.json> --out build/sdetkit/candidate-freeze-readiness.json --format text",
                "schema_version": candidate_freeze_readiness.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "repo",
                    "commit",
                    "repo_fit_schema",
                    "repo_fit",
                    "repo_fit_score",
                    "screen_valid",
                    "promising_screen",
                    "candidate_frozen",
                    "freeze_ready",
                    "readiness_score",
                    "required_evidence",
                    "missing_evidence",
                    "hard_blocks",
                    "recommended_action",
                    "automation_allowed",
                    "merge_authorized",
                    "semantic_equivalence_proven",
                ],
                "stability": "advanced",
            },
            {
                "id": "repo-fit-screen-json",
                "path": repo_fit_screen.DEFAULT_OUT,
                "produced_by": "python -m sdetkit repo-fit-screen --screen-text <screen.txt> --out build/sdetkit/repo-fit-screen.json --format text",
                "schema_version": repo_fit_screen.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "repo",
                    "commit",
                    "candidate_frozen",
                    "screen_only",
                    "score",
                    "fit",
                    "signals",
                    "counts",
                    "risk_notes",
                    "recommended_action",
                    "automation_allowed",
                    "merge_authorized",
                    "semantic_equivalence_proven",
                ],
                "stability": "advanced",
            },
            {
                "id": "maintenance-queue-rollup-json",
                "path": maintenance_queue_rollup.DEFAULT_OUT,
                "produced_by": "python -m sdetkit maintenance-queue-rollup --issue-queue-json <issue-queue.json> --automation-health-json <automation-health.json> --security-followup-json <security-followup-disposition.json> --out build/sdetkit/maintenance-queue-rollup.json --format text",
                "schema_version": maintenance_queue_rollup.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "source_issue_count",
                    "queue_item_count",
                    "review_required_count",
                    "close_candidate_count",
                    "primary_issue",
                    "recommended_next_action",
                    "queue_items",
                    "input_artifacts",
                    "automation_allowed",
                    "merge_authorized",
                    "semantic_equivalence_proven",
                ],
                "stability": "advanced",
            },
            {
                "id": "security-finding-disposition-matrix-json",
                "path": security_finding_disposition_matrix.DEFAULT_OUT,
                "produced_by": "python -m sdetkit security-finding-disposition-matrix --inventory-json <security-findings-inventory.json> --out build/sdetkit/security-finding-disposition-matrix.json --format text",
                "schema_version": security_finding_disposition_matrix.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "inventory_schema",
                    "inventory_status",
                    "source_count",
                    "finding_count",
                    "matrix_row_count",
                    "disposition_counts",
                    "matrix_rows",
                    "recommended_action",
                    "dismiss_allowed",
                    "suppress_allowed",
                    "fix_allowed",
                    "automation_allowed",
                    "merge_authorized",
                    "semantic_equivalence_proven",
                ],
                "stability": "advanced",
            },
            {
                "id": "security-findings-inventory-json",
                "path": security_findings_inventory.DEFAULT_OUT,
                "produced_by": "python -m sdetkit security-findings-inventory --security-json <security-check.json> --out build/sdetkit/security-findings-inventory.json --format text",
                "schema_version": security_findings_inventory.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "source_count",
                    "actual_count",
                    "new_count",
                    "review_count",
                    "by_rule",
                    "by_path",
                    "by_level",
                    "items",
                    "new_items",
                    "recommended_action",
                    "dismiss_allowed",
                    "fix_allowed",
                    "automation_allowed",
                    "merge_authorized",
                    "semantic_equivalence_proven",
                ],
                "stability": "advanced",
            },
            {
                "id": "security-followup-disposition-json",
                "path": security_followup_disposition.DEFAULT_OUT,
                "produced_by": "python -m sdetkit security-followup-disposition --issues-json <issues.json> --security-json <security-check.json> --out build/sdetkit/security-followup-disposition.json --format text",
                "schema_version": security_followup_disposition.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "source_issue_count",
                    "security_followup_count",
                    "security_counts",
                    "finding_severity_counts",
                    "current_finding_count",
                    "new_finding_count",
                    "dispositions",
                    "primary_issue",
                    "recommended_next_action",
                    "automation_allowed",
                    "merge_authorized",
                    "semantic_equivalence_proven",
                ],
                "stability": "advanced",
            },
            {
                "id": "automation-health-json",
                "path": automation_health.DEFAULT_OUT,
                "produced_by": "python -m sdetkit automation-health --issues-json <issues.json> --out build/sdetkit/automation-health.json --format text",
                "schema_version": automation_health.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "status",
                    "source_issue_count",
                    "automation_signal_count",
                    "automation_signals",
                    "lane_counts",
                    "health_state_counts",
                    "primary_signal_issue",
                    "recommended_next_action",
                    "automation_allowed",
                    "merge_authorized",
                    "semantic_equivalence_proven",
                ],
                "stability": "advanced",
            },
            {
                "id": "issue-queue-classifier-json",
                "path": issue_queue_classifier.DEFAULT_OUT,
                "produced_by": "python -m sdetkit issue-queue-classifier --issues-json <issues.json> --out build/sdetkit/issue-queue-classifier.json --format text",
                "schema_version": issue_queue_classifier.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "source_issue_count",
                    "issues",
                    "classification_counts",
                    "recommended_next_issue",
                    "recommended_next_action",
                    "automation_allowed",
                    "merge_authorized",
                    "semantic_equivalence_proven",
                ],
                "stability": "advanced",
            },
            {
                "id": "adoption-surface-json",
                "path": "build/sdetkit/adoption-surface.json",
                "produced_by": "python -m sdetkit adoption-surface --root . --out build/sdetkit/adoption-surface.json --format text",
                "schema_version": adoption_surface.SCHEMA_VERSION,
                "required_fields": [
                    "schema_version",
                    "detected_languages",
                    "package_managers",
                    "test_runners",
                    "ci_systems",
                    "security_tools",
                    "artifact_surfaces",
                    "recommended_proof_commands",
                    "review_first_unknowns",
                    "automation_allowed",
                    "merge_authorized",
                    "semantic_equivalence_proven",
                ],
                "stability": "advanced",
            },
            {
                "id": "doctor-json",
                "path": "build/doctor.json",
                "produced_by": "python -m sdetkit doctor --format json --out build/doctor.json",
                "schema_version": doctor.SCHEMA_VERSION,
                "required_fields": ["schema_version", "ok", "checks"],
                "stability": "public",
            },
            {
                "id": "doctor-evidence-json",
                "path": "build/doctor-evidence.json",
                "produced_by": "python -m sdetkit doctor --emit-evidence --format json --out build/doctor.json",
                "schema_version": doctor.EVIDENCE_SCHEMA_VERSION,
                "required_fields": ["schema_version", "doctor_schema_version", "summary"],
                "stability": "advanced",
            },
            {
                "id": "doctor-evidence-manifest-json",
                "path": "build/doctor-evidence-manifest.json",
                "produced_by": "python -m sdetkit doctor --emit-evidence --format json --out build/doctor.json",
                "schema_version": doctor.EVIDENCE_MANIFEST_SCHEMA_VERSION,
                "required_fields": ["schema_version", "doctor_schema_version", "artifacts"],
                "stability": "advanced",
            },
            {
                "id": "review-json",
                "path": "build/review.json",
                "produced_by": "python -m sdetkit review . --no-workspace --format json --out build/review.json",
                "schema_version": review.SCHEMA_VERSION,
                "required_fields": ["schema_version", "status", "severity"],
                "stability": "advanced",
            },
            {
                "id": "review-operator-json",
                "path": "build/review-operator.json",
                "produced_by": "python -m sdetkit review . --no-workspace --format operator-json --out build/review-operator.json",
                "schema_version": None,
                "required_fields": ["situation", "actions", "artifacts"],
                "stability": "advanced",
            },
            {
                "id": "checks-verdict-json",
                "path": "build/verdict.json",
                "produced_by": "python -m sdetkit gate release --format json --out build/release-preflight.json",
                "schema_version": check_artifacts.VERDICT_SCHEMA_VERSION,
                "required_fields": ["schema_version", "ok", "summary", "check_results_summary"],
                "stability": "public",
            },
            {
                "id": "checks-fix-plan-json",
                "path": "build/fix-plan.json",
                "produced_by": "python -m sdetkit gate release --format json --out build/release-preflight.json",
                "schema_version": check_artifacts.FIX_PLAN_SCHEMA_VERSION,
                "required_fields": ["schema_version", "generated_from", "actions"],
                "stability": "public",
            },
            {
                "id": "checks-risk-summary-json",
                "path": "build/risk-summary.json",
                "produced_by": "python -m sdetkit gate release --format json --out build/release-preflight.json",
                "schema_version": check_artifacts.RISK_SUMMARY_SCHEMA_VERSION,
                "required_fields": ["schema_version", "risk", "summary"],
                "stability": "public",
            },
            {
                "id": "checks-evidence-zip",
                "path": "build/evidence.zip",
                "produced_by": "python -m sdetkit gate release --format json --out build/release-preflight.json",
                "schema_version": check_artifacts.EVIDENCE_SCHEMA_VERSION,
                "required_fields": ["schema_version"],
                "stability": "public",
            },
        ],
    }


def write_index(path: Path) -> None:
    import json

    payload = build_index()
    path.write_text(
        json.dumps(payload, ensure_ascii=True, sort_keys=False, indent=2) + "\n", encoding="utf-8"
    )
